# Generated by Django 4.0.3 on 2022-03-27 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0003_like'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='like',
            table='likes',
        ),
    ]
